### ISSUE TITLE
v0.3.0

### ISSUE THREAD

**Issue by archco** [archco/wise-quotes-client#3]
### Tasks

- [x] Migrating to typescript.
- [x] Using webpack v4.1.1 as build tasker.
- [x] Using Jest as testing tool.
